easy_admin:
    site_name: 'K&E Dimensionierungs-Tools'
    user:
        display_name: true
        display_avatar: false
    design:
        brand_color: '#1ABC9C'
        assets:
            css:
                # ...
                - 'css/admin.css'
    entities:

        Profile:
            class: App\Entity\Profile
            label: 'Accounts'
            list:
                title: "Liste aller Benutzer"
            form:
                fields:
                    - firstname
                    - lastname
                    - company
                    - phone
                    - website
                    - language

        CalculationGroup:
            class: App\Entity\CalculationGroup
            label: 'Calculation Groups'
            list:
                title: "Liste aller Dimensionierungsgruppen"
                actions: ['show']
                fields:
                    - title
                    - description
                    - calculations
                    - isActive
                    - created
            form:
                fields:
                    - title
                    - description
                    - isActive
            show:
                fields:
                    - title
                    - description
                    - isActive
                    - created
                    - createdBy
                    - updated
                    - updatedBy

        Calculation:
            class: App\Entity\Calculation
            label: 'Calculations'
            list:
                title: "Liste aller Dimensionierungen"
                actions: ['show']
                fields:
                    - calculationGroup
                    - title
                    - description
                    - spreadSheet
                    - isActive
            show:
                fields:
                    - calculationGroup
                    - title
                    - description
                    - spreadSheet
                    - isActive
                    - created
                    - createdBy
                    - updated
                    - updatedBy

            form:
                fields:
                    - calculationGroup
                    - title
                    - description
                    - spreadSheet
                    - isActive

        SpreadSheet:
            class: App\Entity\SpreadSheet
            label: 'SpreadSheets'
            templates:
                list: 'admin/listSpreadSheet.html.twig'
            list:
                actions:
                    - 'show'
                    - { name: 'inputs', type: 'route' }
                title: "Liste aller SpreadSheets"
                fields:
                    - name
                    - uid
                    - status
                    - { property: 'isActive', type: 'toggle'}
                    - created
            show:
                fields:
                    - name
                    - uid
                    - isActive
                    - status
                    - created
                    - createdBy
                    - updated
                    - updatedBy
            form:
                fields:
                    - name
                    - uid
